# Generated by Django 6.1.1 on 2026-09-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_descricao_longa_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variacao', 'verbose_name_plural': 'Variações'},
        ),
    ]
